Сдача ТЗ проекта № 7
NikitaChernyaev777/java-kanban pull request #2
Opened 2024-11-21 04:20 UTC by NikitaChernyaev777

2024-11-21 17:10 UTC, afomkina commented on src/history/FileBackedTaskManager.java
> +    void save() {
Лучше добавить модификатор доступа `protected`

2024-11-21 17:11 UTC, afomkina commented on src/history/FileBackedTaskManager.java
> +                if (task instanceof Subtask) {
`instanceof` не соответствует ООП. Нужно придумать, как от него избавиться

2024-11-21 17:13 UTC, afomkina commented on test/history/FileBackedTaskManagerTest.java
> +        Task task = new Task("Задача 1", "Описание задачи 1", Status.NEW);
Повторяющееся создание объектов лучше вынести на уровень класса или в метод `@BeforeEach`, чтобы не дублировать код и сделать его чище

2024-11-21 17:18 UTC, afomkina commented on test/history/FileBackedTaskManagerTest.java
> +        assertEquals(task, loadedManager.getListOfAllTasks().get(0),
Лучше получать задачи по id, а не доставать первую задачу из списка
```suggestion
        assertEquals(task, loadedManager.getTaskById(task.getId()),
```
Так код будет более читаемым

2024-11-25 18:34 UTC, afomkina requested changes

2024-11-25 18:34 UTC, afomkina commented on src/history/FileBackedTaskManager.java
> +        if (task instanceof Subtask subtask) {
Здесь тоже нужно избавиться от instanceof

2024-11-25 18:34 UTC, afomkina commented on src/history/Main.java
> +        Scanner sc = new Scanner(System.in);
Использовать сканер в Main совсем не обязательно, так как пользователь сможет в будующем подключаться в программе по API и использовать нужные методы. Можно вернуть сценарий из прошлой итерации

2024-11-27 10:48 UTC, NikitaChernyaev777 commented on src/history/FileBackedTaskManager.java
> +        if (task instanceof Subtask subtask) {
Да, просмотрел это место (в ТЗ указано, что можно через переопределение - попробую так)

2024-11-28 00:24 UTC, afomkina approved these changes

2024-11-28 16:51 UTC, merged