Сдача ТЗ проекта № 9
NikitaChernyaev777/java-kanban pull request #4
Opened 2024-12-23 06:53 UTC by NikitaChernyaev777

2024-12-23 16:55 UTC, afomkina requested changes

2024-12-23 16:55 UTC, afomkina commented on src/server/BaseHttpHandler.java
> +        sendResponse(exchange, "{\"error\":\"Not Found\"}", 404);
Задание со `"*"`:
Можно создать отдельное перечисление для HTTP кодов и использовать его вместо "голых" цифр. 
Так код будет выглядеть более читаемо и понятней. 
Примеры можно посмотреть в главе [Конструкторы, поля и методы перечисления](https://metanit.com/java/tutorial/3.8.php#:~:text=%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B%2C%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)

2024-12-23 16:55 UTC, afomkina commented on src/server/DurationAdapter.java
Лучше вынести в подпакет adapter

2024-12-23 16:55 UTC, afomkina commented on src/server/LocalDateTimeAdapter.java
Лучше вынести в подпакет adapter

2024-12-23 16:55 UTC, afomkina commented on src/server/BaseHttpHandler.java
Все обработчики лучше вынести в подпакет handler

2024-12-23 16:55 UTC, afomkina commented on src/server/TaskHandler.java
> +            e.printStackTrace();
Нужно удалить этут строчку. Чаще всего печатать весь стектрейс - бесполезно

2024-12-23 16:55 UTC, afomkina commented on src/server/TaskHandler.java
> +                .registerTypeAdapter(java.time.Duration.class, new DurationAdapter())
Нужно испортировать классы `java.time.Duration` и `java.time.LocalDateTime`, а в коде указывать только тип, без полного пути - `Duration` Поправь, пожалуйста, во всех хэндлерах

2024-12-23 16:55 UTC, afomkina commented on test/server/HttpTaskManagerTasksTest.java
> +public class HttpTaskManagerTasksTest {
Лучше еще добавить несколько тестов для epic и subtask. И проверить, что история и prioritized работают корректно. Для этого можно использовать [@Nested классы](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2024-12-24 04:05 UTC, NikitaChernyaev777 commented on src/server/BaseHttpHandler.java
> +        sendResponse(exchange, "{\"error\":\"Not Found\"}", 404);
Не успеваю в этот раз (

2024-12-24 12:27 UTC, afomkina approved these changes

2024-12-24 13:40 UTC, merged